# Generated by Django 5.1 on 2024-09-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_contactno_user_email_user_fname_user_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='username',
        ),
    ]
