# Generated by Django 5.1 on 2024-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('contactno', models.CharField(default='', max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('medical_condition', models.CharField(max_length=50)),
                ('accidental_history', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
