# Generated by Django 5.1 on 2024-09-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userdet_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdet',
            name='accidental_history',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdet',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdet',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdet',
            name='medical_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdet',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
