# Generated by Django 5.1 on 2024-09-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_userdet_accidental_history_alter_userdet_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdet',
            name='accidental_history',
            field=models.CharField(default='no history', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdet',
            name='age',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdet',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userdet',
            name='height',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdet',
            name='medical_condition',
            field=models.CharField(default='no', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdet',
            name='weight',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
