# Generated by Django 5.1 on 2024-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userdet_equipment_userdet_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdet',
            name='otherequipment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
