# Generated by Django 5.1 on 2024-10-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_trainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trainer',
        ),
    ]
