# Generated by Django 5.1 on 2024-10-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_trainerselection_delete_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerselection',
            name='message_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainerselection',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
