# Generated by Django 5.1 on 2024-10-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_trainerselection_message_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerselection',
            old_name='scheduled_time',
            new_name='time_selection',
        ),
    ]
